Dev/help
AllBurst/burstBot pull request #12
Opened 2021-11-02 07:55 UTC by starrysky-eng

2021-11-02 10:00 UTC, MorphTuple requested changes

2021-11-02 10:00 UTC, MorphTuple commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +}
I feel like this can be a lot cleaner but idk necessarily how, @deadshot465 any ideas?

2021-11-02 10:01 UTC, MorphTuple commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +}
Feels like should have a dedicated function to read string from a text file with utf-8 encoding. And also might not necessary to make a const for a filename if it's going to be used once.

2021-11-02 10:39 UTC, deadshot465 requested changes
This pull request is by far one of the worst PRs in this project. **As a help/guide, this is completely unacceptable.** It doesn't even have a guide as to how to play the game, how to progress the game, how to draw and/or play a card, etc. Please rethink about it and rewrite it from ground-up.

今回のPRはあまりにも酷すぎる。**ヘルプ・ガイドとして完全に不合格。**ゲーム遊び方、進み方、カードの出し方など一切ない。書き直してください。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn.txt
> +    自己开启房间等待其他人加入
これは完全に間違っている。
`/start`は今までこのボットを使ったことはない人が初めてサーバーに登録する際に使う命令だ。
ヘルプを書く前に各スラッシュコマンドのコードや説明を確認した？

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn.txt
> +     关于BlackJack21
間違っている。このボットはブラックジャックだけじゃないっていう前提として作ったボットだから。今後他のゲームを追加したら、こちらの説明は実際の内容から外れてしまう。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn.txt
> +     加入他人创建的游戏
もう一度その命令を確認してください。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn_channel.txt
> +    获得每日和每周登陆奖励
ゲームをする最中ログインボーナスを確認するのはおかしくない？

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn_channel.txt
> +    持有的金额
ゲームをする最中自分の手持ちのチップを確認するのはおかしくない？
むしろ今までかけたチップ数の方が確認しがちだろう。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn_channel.txt
> +    自己开启房间等待其他人加入
そもそもゲームに入れる時点で、データベースの中にもうプレイヤーのアカウントがあるとは確定だろう。なんでこの命令がある？

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn_channel.txt
> +     关于BlackJack21
同上。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_cn_channel.txt
> +     加入他人创建的游戏
もうゲームが始まったのにまだ自分のチャンネルから他のゲームに参加する？

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_jp.txt
> +    自らゲームする部屋を作って、他のプレイヤーの参加を待つ
違う。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_jp.txt
> +     他のプレイヤーが作ったゲームに参加
違う。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_jp_channel.txt
> +    毎日もしくは毎週のチップをゲット
同上。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_jp_channel.txt
> +    自らゲームする部屋を作って、他のプレイヤーの参加を待つ
同上。

2021-11-02 10:39 UTC, deadshot465 commented on assets/blackjack_jp_channel.txt
> +     他のプレイヤーが作ったゲームに参加
同上。

2021-11-02 10:39 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +}
Could be implemented in a `Utilities.kt`, but he has to fix help texts first.

2021-11-02 10:39 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +                            blackjackJPText
だからこのボットはブラックジャックだけではないって

2021-11-02 10:39 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +        return Mono.empty()
スラッシュコマンドではなく、プレイヤーが自分自身のチャンネルに`help`を実行する際に表示されるのはこちらだ。でも本当に`help`だけでいい？コールは？オールインは？フォールドは？李くんのゲーム企画書を読んだ？

2021-11-03 05:46 UTC, deadshot465 requested changes
だいぶ改善したけど完成するのはまだ先のことだよ

2021-11-03 05:46 UTC, deadshot465 commented on assets/blackjack_cn_channel.txt
> +  直到本局游戏没有玩家加注后进入开牌阶段
@kinleed2 に確認した方がいいのでは？プランナーと相談した上でコードを書くのは大事。

2021-11-03 05:46 UTC, deadshot465 commented on assets/bot_cn.txt
> +     游戏介绍
テキストファイルの中にtabキーがあるのに、実際にDiscordサーバにて実行したらtabキーがなくなるのはおかしく思わない？

2021-11-03 05:46 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +        } else {
まだ修正していなさそう？

2021-11-03 09:45 UTC, starrysky-eng commented
@kinleed2 7331ebd55047352689abd9ec45eaa44431453a2f

2021-11-03 09:46 UTC, starrysky-eng commented
ゲームの流れ不足点があればどうぞ

2021-11-04 06:56 UTC, starrysky-eng commented
@kinleed2 bb6b4430ed5dd45d3e6c931011637696e67789aa

2021-11-06 16:00 UTC, deadshot465 requested changes
さらに改善したけどちょっとおかしいところはまだあちこちにあるー

2021-11-07 10:21 UTC, starrysky-eng commented on assets/blackJack/CN/draw_cn.txt
> +抽牌
まだまだです　中に何を聞いたほうがいいのかを聞きしたい

2021-11-07 10:22 UTC, starrysky-eng commented on assets/bot/help_cn.txt
> +    *链接至本系列游戏的服务器来进行游玩本作*
了解です

2021-11-07 10:22 UTC, starrysky-eng commented on assets/bot/help_jp.txt
> +    *初めて来られたのプレイヤー様がサーバーに参加する方法*
了解です

2021-11-09 02:53 UTC, deadshot465 requested changes

2021-11-09 02:53 UTC, deadshot465 commented on assets/blackJack/CN/help_allin_cn.txt
> +并取消非弃牌玩家的<等待>状态*
附上「會將檯面上的賭注提高『自己所持賭注 - 初始賭注 - 檯面上目前最高賭注』」可能比較好。

2021-11-09 02:53 UTC, deadshot465 commented on assets/blackJack/CN/help_stand_cn.txt
> +*放弃抽牌并进入<等待>*
改成「等待其他玩家抽牌完成」感覺比較不模稜兩可。

2021-11-09 02:53 UTC, deadshot465 commented on assets/blackJack/CN/help_call_cn.txt
> +跟注量超过自己所持赌注时，继续跟注则自身赌注变为负数*
💡**＜等待＞：等待其他玩家全部跟注或棄牌。**

2021-11-09 02:53 UTC, deadshot465 commented on assets/blackJack/CN/help_raise_cn.txt
> +并取消非弃牌玩家的<等待>状态*
💡**＜等待＞：等待其他玩家全部跟注或棄牌。**

2021-11-09 02:53 UTC, deadshot465 commented on assets/blackJack/JP/help_allin_jp.txt
> +*自分の持ちチップを全てかけて勝負します*
這邊沒有提到等待

2021-11-09 02:53 UTC, deadshot465 commented on assets/blackJack/JP/help_call_jp.txt
> +もしコールするときに自分の掛け金が足りなかった場合チップ枚数をマイナスにすることでオールインできます。*
💡**<待機状態>：…**

2021-11-09 02:53 UTC, deadshot465 commented on assets/blackJack/JP/help_raise_jp.txt
> +誰かがraiseした場合全員が同量のチップを賭ける必要があります*
💡**<待機状態>：…**

2021-11-09 02:53 UTC, deadshot465 commented on assets/bot/help_cn.txt
> +    *链接至本系列游戏的服务器获得100点赌注来进行游玩本作*
冗言贅字

2021-11-09 02:53 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/helper/DataCommand.kt
> +data class DataCommand(@SerialName("command") val command: String, @SerialName("filePath") val filePath: String)
CommandHelpItem

2021-11-09 02:53 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/helper/HelpFunction.kt
> +}
HelperFunctions.kt

2021-11-10 06:09 UTC, starrysky-eng commented
チャックお願いします。

2021-11-10 06:12 UTC, deadshot465 approved these changes
LGTM for now. But merge conflict has to been resolved first.

2021-11-10 06:15 UTC, deadshot465 approved these changes

2021-11-10 06:16 UTC, merged