fix HelpFunctions.kt BlackJack.kt
AllBurst/burstBot pull request #14
Opened 2021-11-10 08:46 UTC by starrysky-eng

2021-11-10 08:47 UTC, starrysky-eng commented
チャックお願いします。

2021-11-10 09:18 UTC, deadshot465 requested changes

2021-11-10 09:18 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/helper/CommandHelpItem.kt
> +    @SerialName("dataMap") val commandHelpItemListItem: List<CommandHelpItemListItem>
`@SerialName`はJSONの中身のキー値と同じしないといけない。それに、`@SerialName`はメンバー変数の名前とJSONのキーの名前が違う場合のみお役に立てる。例えば、`@SerialName("language") val language`、SerialNameと変数の名前は全く同じだから意味がない。

今回のヘルプJSONファイルの中のキー値とデータクラスのメンバー変数の名前は同じだから、`@SerialName`は不要。

2021-11-10 09:18 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +        println(commandList[0] + commandList[1])
デバッグ用の変数とprintlnを削除してください

2021-11-10 09:18 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +                }
毎回`readFile`を呼び出すと効率が悪い。`by lazy`のところに直接的にファイルの中身を読み込んだらいい。

2021-11-10 09:18 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +            .associate { it.language to HashMap(it.commandHelpItemListItem.associate { listItem -> listItem.command to listItem.filePath }) })
ここにファイルパスにマッピングするではなく、ファイルの中身を読み込んでください。

2021-11-10 09:18 UTC, deadshot465 commented on assets/commandList/blackJackCommand.json
> +    "commandHelpItemListItem": [
データクラスの名前だけを`commandHelpItemListItem`にしたらいい。キーの名前はitemとかにしてもいい。

2021-11-10 09:18 UTC, deadshot465 commented on assets/commandList/blackJackCommand.json
> +    "commandHelpItemListItem" :[
ここも同じ。

2021-11-10 15:31 UTC, starrysky-eng commented
チャックお願いします。 @deadshot465

2021-11-10 15:36 UTC, deadshot465 requested changes

2021-11-10 15:36 UTC, deadshot465 commented on assets/commandList/blackJackCommand.json
> +    "lsitItem" :[
誤字（`listItem`）

2021-11-10 15:36 UTC, deadshot465 commented on assets/commandList/blackJackCommand.json
> +    "lsitItem": [
誤字

2021-11-10 15:36 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/helper/CommandHelpItem.kt
> +    val commandHelpItemListItem: List<CommandHelpItemListItem>
なんでJSONファイルの中にキー値は`listItem`なのに、ここは`commandHelpItemListItem`なの？これじゃデーシリアライズができないじゃん

2021-11-10 15:48 UTC, starrysky-eng commented
@deadshot465 チャックお願いします。

2021-11-10 16:16 UTC, deadshot465 requested changes

2021-11-10 16:16 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +            var command: String
この変数をif...elseの外に宣告する理由は？

2021-11-10 16:16 UTC, deadshot465 commented on src/main/kotlin/io/github/allBurst/commands/help/BlackJack.kt
> +                command = if (commandList[1].isEmpty()) {
配列の要素数を確認した？

2021-11-10 23:59 UTC, starrysky-eng commented
check お願いします。 @deadshot465

2021-11-11 02:11 UTC, deadshot465 approved these changes
🙆🏻‍♂️

2021-11-11 02:15 UTC, merged